---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicasets/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.hybridautoscaler.io
  resources:
  - hybridautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.hybridautoscaler.io
  resources:
  - hybridautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.hybridautoscaler.io
  resources:
  - hybridautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
